### ISSUE TITLE
Home Assistant template error

### ISSUE THREAD

**Issue by rachaelbond** [Anrolosia/Shopping-List-with-Grocy#17]
Hi @Anrolosia !

This error has been showing in my HA logs:

Logger: homeassistant.helpers.template
Source: helpers/template.py:625
First occurred: 6 April 2023 at 16:32:03 (58 occurrences)
Last logged: 11:31:35

Template variable error: 'value_json' is undefined when rendering '{{ value_json.qty_in_shopping_list }}'

Any ideas?

**Comment by Anrolosia** [comment]
Hey @rachaelbond 
This happens when a product is deleted through mqtt, after doing the update to 0.5.0, we all had a bunch of those errors. 
It shouldn't happen in a regular usage.
Thanks
