### ISSUE TITLE
add the number of products in the stock

### ISSUE THREAD

**Issue by alfry82** [Anrolosia/Shopping-List-with-Grocy#19]
hello congratulations for the integration. the dashboard is very nice, however it would be useful to see the number of products available within the product button

**Comment by Anrolosia** [comment]
Hey @alfry82 , I just pushed a new release (v0.6.0). With that, every product has now a `qty_in_stock` attribute you can use :)

I'll close that issue, but feel free to open a new one if there is any issue with that new enhancement.
