### ISSUE TITLE
I can't get any product as sensor since I don't use English!

### ISSUE THREAD

**Issue by saya6k** [Anrolosia/Shopping-List-with-Grocy#20]
Hi, I tryed to use your awesome integration to get product as , but I can't get get all product in sensor attribute since I'm not English native. I use Korean Alphabet since I'm Korean, and while I try to get product sensors by mqtt, it floods with logs like this:

2023-05-28 00:28:15.328 WARNING (MainThread) [homeassistant.components.mqtt.discovery] Received message on illegal discovery topic 'homeassistant/sensor/shopping_list_with_grocy_생수_2/state/config'. The topic contains not allowed characters. For more information see https://www.home-assistant.io/integrations/mqtt#mqtt-discovery

Is there any option I can use to get product as sensor?

**Comment by Anrolosia** [comment]
Hey @saya6k , I'll see what I can do, give me few days, thanks!

**Comment by saya6k** [comment]
> Hey @saya6k , I'll see what I can do, give me few days, thanks!

Thank you for your feedback.  I discovered that I can use the English name in the default name field and the Korean name in the 'FriendlyName' userfields that I created for the product sensors. In that way I can get product sensors with English name.

However, it is still inconvenient because the default name field is used throughout Grocy and cannot be customized. Although I can edit the stock overview to display the 'FriendlyName' in front, I hope there is a better way to address this issue.

**Comment by Anrolosia** [comment]
@saya6k I just released a new version (`v0.6.1`), that should fix your issue. 
Please test it and let me know if everything is working now

**Comment by saya6k** [comment]
@Anrolosia Great! Now I can get my product sensors! Thank you for your great reponse!

**Comment by Anrolosia** [comment]
Awesome! You're welcome, enjoy this module. Have a great one!
