### ISSUE TITLE
Config entry 'ShoppingListWithGrocy' for shopping_list_with_grocy integration not ready yet: can only concatenate str (not "int") to str; 

### ISSUE THREAD

**Issue by renarena** [Anrolosia/Shopping-List-with-Grocy#22]
The Shopping List with Grocy integration is not loaded and in the core log i see this error:
`Config entry 'ShoppingListWithGrocy' for shopping_list_with_grocy integration not ready yet: can only concatenate str (not "int") to str; `

I use latest version from HA, grocy and this integration (0.7.0).

**Comment by Anrolosia** [comment]
Hey @renarena , could you provide the full stack trace error please? Including filename and line. Because I didn't touch anything on the config flow on that version. Thanks

**Comment by renarena** [comment]
Ok, one need to switch off debug logging to see the log. Was already wondering about it.
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/shopping_list_with_grocy/__init__.py", line 189, in _async_update_data
    return await self.api.retrieve_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/shopping_list_with_grocy/apis/shopping_list_with_grocy.py", line 553, in retrieve_data
    await self.parse_products(self.final_data)
  File "/config/custom_components/shopping_list_with_grocy/apis/shopping_list_with_grocy.py", line 233, in parse_products
    shopping_lists["list_" + shopping_list_id] = {
                   ~~~~~~~~^~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "int") to str
```

**Comment by Anrolosia** [comment]
Hey @renarena , I'm curious, do you have any shopping list defined on your Grocy's instance?? Thanks

**Comment by renarena** [comment]
yes, of course

**Comment by Anrolosia** [comment]
And does the bug still occur with v0.7.1?

**Comment by renarena** [comment]
its working now :-)

**Comment by Anrolosia** [comment]
Perfect ^^
