### ISSUE TITLE
Default quantity unit purchase

### ISSUE THREAD

**Issue by anha7196** [Anrolosia/Shopping-List-with-Grocy#24]
Hi Anrolosia!

Another enhancement suggestion that i would appreciate greatly: The possibility to use "Default quantity unit purchase" instead of "Quantity unit stock" in the shopping list. For example for some items like flour i have "grams" as the stock unit and "package" as the purchase unit. That's impractical  in the shopping list as i might have 200g (one package) in the shopping list... What do you think?

**Comment by Anrolosia** [comment]
Hey @anha7196 

I might misunderstand something... The default quantity unit purchase is always used by default when a product is added to the shopping list (I just tested that). So in your case, you will not add 200x your flour, but only once for a package.

Could you clarify please?

**Comment by anha7196** [comment]
I'm talking about whats viewed in the shopping list, or in the list_X_qty and sensor amount. If i add one package of flour in the grocy web shopping list, there will 500 in the shopping list in Hass as the plugin views the grams, not the packages. In the Grocy web view it will be viewed as 1 package. 
Maybe this is somethoing that should be solved in the dashboard ui, but this is an example sensor in my HA now:

This is a nice example as there is two packages of coffee in one list (2) and one on another (7).
As you can see, the amounts is in grams. It would be great to have the packages available as well. And maybe the unit as well. 


```
Kaffe
	2125 	group: Dryck
list_2_note: 
list_2_qty: 1275
list_2_shop_list_id: 2475
list_7_note: 
list_7_qty: 850
list_7_shop_list_id: 804
list_count: 2
location: Skafferi
product_id: 71
product_image:  [cut]
qty_in_stock: 903568
topic: shopping-list-with-grocy/products/shopping_list_with_grocy_product_v1_71/state
icon: mdi:cart
friendly_name: Kaffe
```

Hope this makes it clearer and that i did not miss something obvious.

**Comment by Anrolosia** [comment]
Ok, got it! Let me see what I can do :)

**Comment by anha7196** [comment]
Wow, amazingly quick! 
I only had time now for a quick check, but it seems to work as intended! I'll try it out more during the weekend.

**Comment by Anrolosia** [comment]
Awesome! I'll close that ticket, feel free to open a new one if you find a bug. Cheers!
