### ISSUE TITLE
MQTT Port not available

### ISSUE THREAD

**Issue by sushibagel** [Anrolosia/Shopping-List-with-Grocy#27]
Hi I'm working on trying to get this setup in my home assistant instance but the MQTT doesn't have an option for the port I use. Is there an option to add a custom port?

**Comment by Anrolosia** [comment]
Hello @sushibagel 
There is not right now, but it can definitely be added for a next update, I'll try to make it happen asap :)

**Comment by Anrolosia** [comment]
@sushibagel The custom port is now available in release v0.9.0 !
