### ISSUE TITLE
Problems with component configuration

### ISSUE THREAD

**Issue by casasimovero** [Anrolosia/Shopping-List-with-Grocy#29]
I installed the official Grocy component and opened port 9192 as per the HACS integration instructions. Once configured the interaction still doesn't work, could you help me?
![Cattura](https://github.com/Anrolosia/Shopping-List-with-Grocy/assets/96723753/93b63dde-3da5-4b92-8cf6-5397537a29af)
![Cattura1](https://github.com/Anrolosia/Shopping-List-with-Grocy/assets/96723753/46e35178-8714-4936-adcf-58d28ed46b23)
after clicking on the send button
![Cattura2](https://github.com/Anrolosia/Shopping-List-with-Grocy/assets/96723753/5297b324-53fb-4457-8b5e-1185110b572e)
The component at fault appears to me
![Cattura3](https://github.com/Anrolosia/Shopping-List-with-Grocy/assets/96723753/0b444e2c-628c-4e77-b359-686a4008b600)
Could it be the fault of the fact that I set the Italian language?
Sorry for my English

**Comment by casasimovero** [comment]
in the MQTT server register, this wording also appears as a component in HA IOS
![Cattura4](https://github.com/Anrolosia/Shopping-List-with-Grocy/assets/96723753/590e69c3-6b8c-44a8-ae93-175257c7897d)

**Comment by Anrolosia** [comment]
Hello @casasimovero ,

if you try to access in a browser your ip : your port, is it working? It shouldn't be linked to italian language. Also, any specific error in System logs in HA?

Thanks

**Comment by zjleblanc1** [comment]
I'm having the same issue. Grocy works fine but this integration won't seem to connect. My logs look identical. @casasimovero did you get it working?

**Comment by Anrolosia** [comment]
Awesome! So I guess this ticket could be closed, right? Have a great one!
