### ISSUE TITLE
Qty Aggregated as attribute for parent product sensor

### ISSUE THREAD

**Issue by saya6k** [Anrolosia/Shopping-List-with-Grocy#32]
Hi again,

Thanks for product sensor attributes, but I have some enhancement.

In Grocy, app adds all the child product quantity inside to show as quantity in summary. '∑' represents it's sum.

However, for parent product sensors produced by Shopping list with Grocy, it only show attribute.qty_in_stock as '0', which is useless since attribute.no_own_stock = 1 already shows it has now own stock.

And it is cumbersome to add calculation in Lovelace. I wish if integration supports this.

So in product sensor for parent product, I think it should show value of sum. Like Grocy app, adding ’∑‘ can represent it's sum of child product's quantity.

And I wish I can get some attributes in boolean, int or float, not string.

**Comment by Anrolosia** [comment]
Hello @saya6k !
I pushed a version 0.12.x where you'll be able to find both ```aggregated_stock``` and ```parent_product_id``` new attributes for each of your products
I hope it will answer your needs.
Thanks!
