### ISSUE TITLE
binary_sensor.updating_shopping_list_with_grocy is not created

### ISSUE THREAD

**Issue by iikkamerilainen** [Anrolosia/Shopping-List-with-Grocy#33]
Hi! I installed the integration, but binary_sensor.updating_shopping_list_with_grocy that is mentioned in the docs and used by the sample card wasn't created. Other sensors like sensor.products_shopping_list_with_grocy were. Tried enabling debug logging for the integration, but logs show nothing.

**Comment by Anrolosia** [comment]
Hi @iikkamerilainen , have you tried to reboot HomeAssistant maybe? It should be created as the other sensors. Thanks

**Comment by iikkamerilainen** [comment]
Yep I did try restarting, no effect.

**Comment by Anrolosia** [comment]
Could you try to call the service ```shopping_list_with_grocy.refresh_products``` please?
It should be created at the first call.
Thanks

**Comment by iikkamerilainen** [comment]
I called that service using the Developer Tools -> Services with empty data, but binary_sensor.updating_shopping_list_with_grocy did not appear.

**Comment by Anrolosia** [comment]
that is so strange... It's automaticaly created by MQTT integration. Do you have correct integration with MQTT? Do you see your products?

**Comment by 1sthandy** [comment]
Hi, i have the same error. New System with Grocy on same host.

Home Assistant 2023.10.5
Supervisor 2023.10.1
Operating System 11.1
Frontend 20231005.0 - latest

**Comment by Anrolosia** [comment]
@1sthandy yup, this is why I asked about the integration with MQTT, if it was correctly installed and configured.

So I guess fixing your MQTT integration fixed your issue with that module?

@iikkamerilainen could you check on your side also please?

Thanks

**Comment by iikkamerilainen** [comment]
Yep that was it! Had a bad MQTT config, fixing it created the entity. Should probably log an error message. Thanks for the help!

**Comment by Anrolosia** [comment]
Awesome! I'll close the ticket then
I think I will update the documentation to include that :)
Thank you
