### ISSUE TITLE
show Quantity Unit in Product sensor as string.

### ISSUE THREAD

**Issue by saya6k** [Anrolosia/Shopping-List-with-Grocy#34]
Hi, I've been working on making lovelace settings to show dashboard like grocy app.

In individual product sensor, it's showing quantity unit id so I should define id to string in Home Assistant once again.

I wish I can get a quantity unit as string.

**Comment by Anrolosia** [comment]
I pushed an update (v0,13,0) to add both qty_unit for purchase and store.
