### ISSUE TITLE
Can't track amount open in product sensor

### ISSUE THREAD

**Issue by saya6k** [Anrolosia/Shopping-List-with-Grocy#35]
Hi,

I can't track amount opened in product sensor.

Also, I want to track where the product is, since in Grocy it can track product transfer.

Thanks again for great effort.

**Comment by Anrolosia** [comment]
I will add something for the opened status :)

For the location, there is an attribute ```location``` in each sensor, so I don't understand what you're talking about when you say "I want to track where the product is"

Thanks

**Comment by Anrolosia** [comment]
I pushed an update (v0.13.0) with 2 new attributes ```qty_opened``` and ```aggregated_opened``` in case you have parent products
