### ISSUE TITLE
Feature Request: Consume Location as attribute

### ISSUE THREAD

**Issue by saya6k** [Anrolosia/Shopping-List-with-Grocy#36]
Hi,

I want consume location as attribute.

In that way, if I check move on open, I can locate the product amount that is opened and in consume location.

That improve the ability to use Grocy in Home Assistant, like hosting seperate dashboard to satellite kiosk in location.
And it can show opened product and opened amount(which is already presented), with auto-entities or something.

Again, thanks for great effort.

**Comment by Anrolosia** [comment]
Hey @saya6k ,

I just pushed v0.13.1 where you can find a ```consume_location``` attribute.

Thanks!
