### ISSUE TITLE
Feature Request: Having qty_unopened as product sensor attribute

### ISSUE THREAD

**Issue by saya6k** [Anrolosia/Shopping-List-with-Grocy#37]
Hi,

I think having qty_unopened(or amount_unopened) can improve attribute.

It is very common practice to store unopened amount as separate value. And many Home Assistant card does not support attribute templating. So, it is not easy to get unopened amount in Home Assistant. If product sensor supports unopened amount as separate attribute, it will be much easier to get value.

**Comment by Anrolosia** [comment]
Done and pushed with release v0.14.0
