### ISSUE TITLE
Worked yesterday, not today.

### ISSUE THREAD

**Issue by squito1** [Anrolosia/Shopping-List-with-Grocy#42]
Please help. It must be missing something simple. I have redownloaded, restarted, and reconfigured and nothing helps. Grocy is working properly but now Shopping list is not. 
Error : Failed setup, will retry: Cannot connect to host 192.168.1.222:9192 ssl:default [[SSL] record layer failure (_ssl.c:1000)] but I have deactivated all of the SSL as directed.
![Shopping list error](https://github.com/user-attachments/assets/4635850a-263b-4b19-ba7c-117fed753762)
![Shopping list config](https://github.com/user-attachments/assets/c87b451e-cba6-4dd6-95a7-f1e05f316e0b)
![grocy config](https://github.com/user-attachments/assets/086f4e43-e0ae-4b73-9ae5-09c9a9bba0f7)

**Comment by Anrolosia** [comment]
As mentioned in the doc:
```You SHOULD use https if your Grocy's module is configured to use SSL (even if you don't have any certificate). Use http:// if it's not checked```
I can see on your Grocy's screenshot the SSL checkbox is not checked. So try to replace https with http or check the SSL checkbox and let me know if works

**Comment by squito1** [comment]
Well, it's working again thank you!

I did receive this warning message though. "Detected that custom integration 'shopping_list_with_grocy' calls async_forward_entry_setup for integration, shopping_list_with_grocy with title: ShoppingListWithGrocy and entry_id: 01JABXRBM83PDB1GT44NQYFF55, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/shopping_list_with_grocy/__init__.py, line 70: hass.async_create_task(, please create a bug report at https://github.com/Anrolosia/Shopping-List-with-Grocy/issues"

Anyway, guess I misread the http to https part. I interpreted it as leave as https just turn off the verify function. Have a great day!

**Comment by Anrolosia** [comment]
Awesome! 

Yeah, I really need to push the update for that :) Thanks a lot and have a great one!
