### ISSUE TITLE
Missing shopping list items

### ISSUE THREAD

**Issue by rachaelbond** [Anrolosia/Shopping-List-with-Grocy#6]
If a shopping list item has a quantity value < 1 (e.g. 0.5kg flour) than it isn't shown in the list

**Comment by Anrolosia** [comment]
Hey @rachaelbond , thanks for raising that issue, I'll take a look asap

**Comment by Anrolosia** [comment]
Just to be clear, you're talking about the card example I provided? Because I tested, and if I replace 
```
          filter:
              include:
                - entity_id: sensor.shopping_list_with_grocy_.*
                  attributes:
                    qty_in_shopping_list: '>=1'
                  not:
                    attributes:
                      note: out_of_stock
```
by
```
          filter:
              include:
                - entity_id: sensor.shopping_list_with_grocy_.*
                  attributes:
                    qty_in_shopping_list: '>0'
                  not:
                    attributes:
                      note: out_of_stock
```
it works
![image](https://user-images.githubusercontent.com/1843399/211178803-a3c6b44c-ef2f-4bc8-bdc0-004e423a3e79.png)

**Comment by rachaelbond** [comment]
Doh!! My bad :( It never occurred to me to check the filter condition. So sorry!

**Comment by Anrolosia** [comment]
It's fine ^^ I'll modify the readme later today to fix that.
Have a great day

**Comment by Anrolosia** [comment]
Documentation has been updated! I'll close that ticket. Have a great one!
