### ISSUE TITLE
Grocy URL

### ISSUE THREAD

**Issue by MinnowKnight** [Anrolosia/Shopping-List-with-Grocy#9]
No matter which URL I use, I get the error "Grocy's URL is invalid, please use valid URL (http:// or https:// with either domain name or ip address)".

I am using the Grocy Add-On, and the Grocy Custom Integration, both of which installed and function without a hitch.

**Comment by Anrolosia** [comment]
I can't help you if you don't provide more info or at least a screenshot.
How did you configure Shopping List with Grocy?

**Comment by MinnowKnight** [comment]
This is when I go to add the integration, before any configuration has happened, which I installed through HACS. I've used the URL with the port, without the port, and with the generic homeassistant port. I have the SSL turned off in both Grocy Add-On & Grocy Integration

![image](https://user-images.githubusercontent.com/109559921/216849663-9c25c0ca-cb15-480e-9643-e7e96607759e.png)

**Comment by Anrolosia** [comment]
Without a screenshot of the configuration used, I still can't help...
Also, have you read this part of the README?
![image](https://user-images.githubusercontent.com/1843399/216850942-9487a29d-11c5-42f4-a85b-2933057a0c43.png)

**Comment by MinnowKnight** [comment]
I had read through, but I figured it out. Thank you for the assistance, the
issue was I was using the localhost (http://homeassistant:9192) instead of
the direct IP.

Cheers

**Comment by Anrolosia** [comment]
I was expecting something like this, I'm glad you were able to fix it! If you have any issue or feedback, don't hesitate to open a ticket.
I'll close this one since that was fixed.
Have a great one!
